####################################################
#
# ITEM DISPLAY FORMAT VARIABLES
# %basematerial% - The name of the item's material in Minecraft
# %mythicmaterial% - The name of the item's material defined in language.yml
# %itemtype% - The type of item it is (sword/axe/helmet/boots/misc, etc.)
# %basicprefix% - A random basic prefix from prefix.txt
# %basicsuffix% - A random basic suffix from suffix.txt
# %tiername% - The name of the item's tier.
#
####################################################
options:
  safeEnchantsOnly: true
  customItemsSpawn: false
  customItemsOnly: false
  autoUpdate: false
display:
  itemNameFormat: '%tiername% %itemtype%'
percentages:
  mobSpawnWithItemChance: 0.25
worlds:
  enabled: false
  generate:
  - world
  - world_nether
  - world_the_end
  use:
  - world
  - world_nether
  - world_the_end