main: com.conventnunnery.plugins.MythicDrops.MythicDrops
name: MythicDrops
version: 1.0.0b@VERSION@
author: ToppleTheNun
commands:
    mythicdrops:
        description: Gives user a MythicDrops item.
        aliases: [md,mythic]
        usage: /<command>
permissions:
    mythicdrops.command.spawn:
       description: Allows user to use "/md spawn [tier|*] [amount]"
       default: op
    mythicdrops.command.give:
       description: Allows user to use "/md give <player> [tier|*] [amount]"
       default: op
    mythicdrops.command.reload:
       description: Allows user to use "/md reload"
       default: op